---
title: "Деятельность центра"
back: '/'
---

В течении всего года в центре проходят учения, занятия и буддийские ритуалы.
Как правило жизнь центра проходит по уже давно устоявшимся правилам.

Осенью и весной в рамках годового турне по Дхарма-центрам городов России
Досточтимый Геше Джампа Тинлей посещает наш центр. Учения даются с середины
марта и до середины апреля весной и в течении всего ноября осенью. Занятия
проходят три дня в неделю. По понедельникам и четвергам в 19:00 для всех
желающих, по субботам в 12:00 для имеющих какое-либо тантрическое посвящение
или хотя бы благословение. Учения проводятся бесплатно.

Три раза в год проходят общероссийские ретриты под руководством Гешела, на
которых собираются его ученики со всех городов России. Во начале ноября,
в праздничные и выходные дни проходит осенний ретрит посвященный учениям по
тренировке ума, проводящийся в последние годы в в Подмосковном Ерошово.
В середине декабря - зимний ретрит по пустоте, традиционно проходящий
в Бедске под Новосибирском. Длительность осеннего и зимнего ретритов 3-4
дня. Летом в медитацинном центре близ поселка Заречный на берегу Байкала
с конца июля и по конец августа проходит байкальский ретрит.

В течении всего года в центре проводятся различные занятия. Расписание занятий
организовано по дням недели. Также 19:00 в 10 и 25 дни лунного месяца и в дни
буддийских праздников проводятся подношение Цог. При этом регулярное занятие
проводящееся в тот же день и то же время отменяется. Занятия по дхарме не
проводятся в время учений Геше-ла и время ретритов. Занятия по тибетскому языку
могут прерываться в течении года в связи с отъездом преподавателя.  Занятия по
йоге и Цоги обычно проходят круглый год. Точные даты сроков текущих
и запланированных занятий, отмены занятий и точное расписание на текущую
и будущую неделю можно найти на странице link:/timetable?offset=0[расписания].
Также следите за link:/news?top=true[новостями].

=== Недельное расписание

[cols=">.<10,<90"]
|===
|Понедельник
|

|Вторник
|19:00 - 21:00 link:/text/yoga/[Йога]

|Среда
|19:00 - 21:00 Изучение дхармы

|Четверг
|19:00 - 21:10 link:/text/yoga/[Йога]

|Пятница
|19:00 - 21:00 Тибетский язык

|Суббота
|

|Воскресенье
|
11:00 - 13:00 Видеопросмотры +
14:00 - 16:00 Изучение дхармы +
18:00 - 20:00 Тибетский язык

|===
