---
title: "Ретрит по Лоджонгу под руководством Досточтимого геше Джампа Тинлея - 2016"
publish_date: "2016-09-04"
buddha_node: "395"
---

Дорогие друзья! Как обычно, в этом году в Подмосковье состоится традиционный
осенний ретрит, на котором Досточтимый Геше Джампа Тинлей дарует учение по
практике Лоджонг. Практика Лоджонг, тренировка ума, является сущностным учением
Махаяны. Целью этой практики является уменьшение себялюбия, взращивание
подлинной заботы о других и преобразование неблагоприятных обстоятельств и
негативных факторов в духовный путь. В наше время пяти упадков практика
тренировки ума, Лоджонг, является необходимым условием для достижения каких бы
то ни было духовных реализаций. Досточтимый Геше Тинлей является одним из
выдающихся держателей непрерывной линии передачи этого учения, восходящей к
величайшим мастерам прошлого.

Учение по практике Лоджонг будет проходить с 3 по 6 ноября в подмосковном
http://www.ershovo.su[пансионате «Ершово»], располагающегося на территории
бывшей графской усадьбы Олсуфьевых в живописном месте недалеко от Звенигорода.
Учение на ретрите будет передаваться бесплатно.

<<<

== Расписание

[cols="2,2,8"]
|===

.2+| Чт, 3 ноября
| 15:00 - 19:00 | регистрация участников
| 19:30 - 21:30 | первая лекция

.3+| Пт, 4 ноября
| 10:00 - 12:00 | утренняя лекция
| 15:00 - 17:00 | дневная лекция
| 19:30 - 21:30 | вечерняя лекция

.3+| Cб, 5 ноября
| 10:00 - 12:00 | утренняя лекция
| 15:00 - 17:00 | дневная лекция
| 19:30 - 21:30 | вечерняя лекция

.2+| Вс, 6 ноября
| 10:00 - 12:00 | утренняя лекция
| 15:00 - 16:30 | заключительная сессия

|===

== Проживание

В пансионате есть номера разного уровня комфорта. В номерах *стандарт*,
*комфорт* и *полулюкс* есть душ, туалет, холодильник и телевизор. В *эконом*
корпусах все удобства расположены на этаже, количество номеров в них
ограничено. Проживание в пансионате оплачивается за три для, в оплату включен
трехразовый шведский стол с вегетарианскими и мясными блюдами. В случае
большого количества участников ретрита возможно подселение в номера при
согласии проживающих.

[width='70%',cols="<1,^1", grid="rows", frame="none"]
,===
Номер, Стоимость чел/сутки(3 суток)

одноместный *стандарт*,         2057 (6171) руб
двух- и трехместный *стандарт*, 1611 (4833) руб
двухместный *комфорт*,          1879 (5637) руб
двухместный *полулюкс*,         1968 (5904) руб
,===

Для детей до 12 лет также действуют специальные цены пансионата.

Поселиться в пансионат на время проведения ретрита вам помогут координаторы из
нашего центра. Укажите необходимую информацию
в https://goo.gl/forms/8gTdTQy3A7nWht3s1[электронной форме] и координатор
свяжется с вами. Либо вы можете связаться с координатором самостоятельно.
Зарегистрироваться на ретрит и *оплатить проживание необходимо до 26 октября
2016 года*, иначе мы не сможем вас заселить.

Бронирование и оплата осуществляется поэтапно:

1. свяжитесь с координатором, уточните свободные места и забронируйте номер
2. перечислите оплату по реквизитам из приложения и сообщите о факте оплаты
3. координатор проведет оплату в пансионат и сообщит о факте регистрации

Также вы можете обратиться непосредственно в link:/content/?q=node/3[наш центр]
по средам и пятницам с 19:00 до 21:00 и по воскресеньям с 16:00 до 18:00.

[role='good-news']
====

Если у вы хотите проспонсировать участие в ретрите тех, кто хотел бы принять
участие, но не имеет финансовой фозможности, то вы можете сделать это
обратившись к координатору.

====

== Проезд до места

* *Общественным транспортом* Сначала https://rasp.yandex.ru/-/CVcVRWJi[электричкой]
 от Белорусского вокзала до станции Голицыно (50 минут), затем на
https://rasp.yandex.ru/-/CVcVR0L6[маршрутном такси №22] до конечной остановки
«Дом отдыха «Ершово» (40 минут). Электрички ходят с частотой 15-20 минут,
маршрутные такси - 15 мин.

* *На машине* По Новорижскому шоссе до пересечения с малой московской
кольцевой дорогой А107, на развязке свернуть по указателю в сторону
Звенигорода. В Звенигороде на втором светофоре повернуть направо, далее по
дороге через поселок Супонево до пансионата Ершово.

* *Заказным автобусом* В день открытия ретрита 3 ноября из Москвы от
метро Добрынинская в 13:30 пойдут заказные автобусы до места (1.5 часа).
Забронировать и оплатить место в автобусе нужно заодно с оплатой проживания.
Для организации группового трансфера от вокзалов и аэропортов обращайтесь
к координатору.

== Заселение

Регистрация будет проходить в административном корпусе пансионата в день
открытия ретрита 3 ноября с 15:00 до 19:00 и с 21:30 до 22:00.  Для заселения
в пансионат необходим паспорт. Мы может заранее заполнить
link:/news/2016-09-04/ershovo_form.doc[анкету для поселения]. При регистрации
также нужно внести организационный взнос на проживание и питание Учителя,
и другие расходы в размере 300 рублей. Cтуденты, пенсионеры и инвалиды, а также
дети до 16 лет от уплаты организационного взноса освобождаются.

== Приложение

===  Координаторы

[cols="2,2,2,8"]
|===
| Имя      | Почта                     | Телефон         | Регион

| Ольга    | ol.tsarenko@list.rui      | 8-916-122-43-53
.3+| Москва и Московская область
| Марина   | jerom1@yandex.ru          | 8-916-176-42-32
| Наталья  | ershovo2016@gmail.com     | 8-915-320-19-95

| Анна     | ametista07@mail.ru        | 8-903-689-05-50
| Европейская часть – Калмыкия, Сочи, Ростов, С.-Петербург, Сыктывкар, Воронеж,
  Ярославль и т.д., а также Украина, Белоруссия, Литва и т.п.

| Ольга    | olga.zaugolkina@gmail.com | 8-916-834-62-68
| Сибирь и Урал – Томск, Новосибирск, Омск, Петропавловск,
  Уфа, Магнитогорск, Екатеринбург и т.п.

| Наталья  | Tasha-retrit@mail.ru      | 8-926-385-79-97
| Восток – Забайкалье, Бурятия, Тува, Иркутск, Красноярск и т.п.

|===

=== Реквизиты

[width='60%', cols=">1,<3a", frame='none']
|===
|Получатель:         | *Местная религиозная организация - Московский Буддийский Центр Ламы Цонкапы Московский банк Сбербанка России*
|Банк получателя:    | ОАО "Сбербанк России" г. Москва
|Р/с                 | № 40703810738250121311
|Кор/сч              | № 30101810400000000225
|БИК                 | 044525225
|ИНН                 | 7731244887
|КПП                 | 772501001
|Назначение платежа: | *«оплата за семинар [ваш город, фамилия, инициалы], без НДС»*
|===

Оплата производится *только в рублях РФ*. Тщательно проверьте графу назначения
платежа, при *фактическое ошибке* мы не сможем принять ваш платеж.  Пример
правильно заполненной графы: *«оплата за семинар Великий Новгород, Иванов И.И.,
без НДС»*.
