---
title: "Занятия по теории и практике буддизма"
publish_date: "2016-08-10"
buddha_node: "394"
---

Дорогие друзья! С 31 августа 2016 года в московском буддийском Центре Ламы
Цонкапы открывается новый курс занятий по буддийской теории и практике. Занятия
будут проходить вплоть до начала ежегодного всероссийского ретрита по
тренировке ума (2 ноября). Занятия бесплатны и предназначены для всех желающих.

*Внимание*, расписание было изменено: занятия для начинающих перенесены
с воскресенья на пятницу, а занятия по философии - наоборот, с пятницы
на воскресенье.

<<<

== Шаматха и логика

Изучение и практика однонаправленной концентрации (шаматхи).
Изучение буддийской логики.

по *средам* с 19:00 до 21:00

== Курс для начинающих

Курс знакомит слушателей с базовыми темами буддизма махаяны.

по *пятницам* с 19:00 до 21:00.

[cols=">1,2,20"]
|===
| 2  | сентября  | вводное занятие "Буддизм: путь к жизни, полной смысла."
| 9  | сентября  | Четыре благородные истины, занятие 1
| 16 | сентября  | Четыре благородные истины, занятие 2
| 23 | сентября  | Карма
| 30 | сентября  | Прибежище, занятие 1
| 14 | октября   | Порождение любви и сострадания
| 21 | октября   | Тренировка ума (лождонг)
| 28 | октября   | Три основы пути
|===

== Философия

Изучение воззрения четырех филосовских школ.

по *воскресеньям* с 11:00 до 13:00

[cols=">1,2,20"]
|===
| 4  | сентября  | Общий обзор буддийских философских школ
| 11 | сентября  | Вайбхашика, занятие 1
| 18 | сентября  | Вайбхашика, занятие 2
| 25 | сентября  | Вайбхашика, занятие 3
| 2  | октября   | Саутрантика
| 16 | октября   | Читтаматра, занятие 1
| 23 | октября   | Читтаматра, занятие 2
| 30 | октября   | Читтаматра, занятие 3
|===

== Ламрим

Занятия по тексту великого Учителя прошлого Дже Цонкапы "Ламрим
-Ченмо". Последовательно по всем темам Ламрима.

по *воскресеньям* с 14:00 до 16:00
