---
title: "Ссылки"
back: '/'
---

== Сайты центров Досточтимого Геше Джампа Тинлея в других городах

http://www.green-tara.ru/[Зеленая Тара] — центр в Улан-Удэ.
Содержит множество полезных материалов по буддийской теории и практике.

http://tushita.ru/[Тушита] — центр в Уфе.

http://tara-buddha.info/[Тара] — центр в Омске.

http://maitreya-nsk.narod.ru/[Майтрея] — центр в Новосибирске.

http://evajrapani.narod.ru/[Ваджрапани] — центр в Екатеринбурге.

http://chakrasamvara.ru/[Чакрасамвара] — центр в Красноярске.

== Рускоязычные ресурсы

http://www.dalailama.ru/[Его Святейшество Далай-лама XIV] —
Официальный сайт Его Святейшества Далай-ламы XIV на русском языке.

http://geshe.ru[Официальный сайт Досточтимого Геше Джампа Тинлея и
Централизованной религиозной буддийской организации "Дже Цонкапа"]

http://lib.geshe.ru/[Электронная библиотека] — Обширное собрание
электронных книг и аудиозаписей лекций Досточтимого Геше Тинлея начиная
с 1994 года.

http://www.jetsonkhapa.ru/[Издательство "Дже Цонкапа"] — Издание
аутентичной литературы буддийской тематики.

http://www.facebook.com/MoscowBuddhistCenterofLamaTsonkapa?ref=digest_email[Страница
московского буддийского Центра Ламы Цонкапы на Фейсбуке]

http://savetibet.ru/[Savetibet] — Центр тибетской культуры и информации в Москве

http://www.berzinarchives.com/[Архив Алекса Берзина] на русском языке.
Новый сайт, где выложены статьи и переводы, посвященные сутре и тантре
известного буддийского переводчика и ученого А. Берзина

http://www.buddhismofrussia.ru/books/109/[Ламрим Ченмо] — Здесь выложены
все пять томов Ламрим Ченмо ламы Цонкапы в формате pdf.

http://www.theosophy.ru/lib/budd-lit.htm[Буддийская литература] на сайте
«Теософическое общество и теософическое движение в России»

http://sangharussia.ru[Буддийская традиционная Сангха России] —
Официальный сайт Буддийской традиционной Сангхи России. Содержит
информацию о буддизме и буддийском духовенстве Бурятии.

http://www.buddhismofrussia.ru[Буддизм России, Нартанг] — Сайт журнала
"Буддизм России" и издательства "Нартанг".

http://dazan.spb.ru/["Дацан Гунзэчойнэй" - буддийский храм Cанкт-Петербурга]
Новости и текущие события в дацане и в городе. Основы буддийского
учения. Жизнеописания учителей, лекции. Библиотека. Ответы настоятеля и
лам дацана на вопросы. Форум.

http://online.stack.net/~alex/[Буддийская живопись Бурятии] — Сайт Музея
истории Бурятии с уникальными фотографиями буддийских танок, изданных в
альманахе "Буддийская живопись Бурятии".

http://learntibetian.wordpress.com[Изучение тибетского языка] —
Программы для изучения тибетского языка, учебники и материалы для
занятий.

http://tibetan.bitecs.ru/[Проект Tibetan] — материалы для изучения
тибетского языка.

== Англоязычные ресурсы

http://moscow-buddha-temple.ru[Строительство буддийского храма в
Отрадном]

http://www.fpmt.org/[FPMT] — Официальный сайт Фонда Традиции Сохранения
Махаяны (Foundation for Preservation of Mahayana Tradition) —
международной сети центров традиции Гелуг, основанной Ламой Еше и Ламой
Сопой Ринпоче.

http://www.lamayeshe.com/[Lama Yeshe Wisdom Archive] — Содержит учения
Ламы Еше и Ламы Сопы, а также ряда учителей традиции Гелуг. На сайте
можно получить оперативную информацию о новых книгах, а также подать
заявку на рассылку бесплатных брошюр.

http://www.tibetgame.com/[The Tibet Game] — Увлекательная онлайн-игра —
путешествие по современному Тибету. Делая добрые дела, вы сможете
достичь там нирваны. Попутно вы увидите качественные фотографии
современного Тибета и получите информацию об этой стране.

http://www.tibet.net/[Tibetan's Virtual Homeland] — Новый сайт, который
содержит разнообразную информацию о Тибете и тибетской культуре.

http://www.tibet.org/[Tibet Online] — Информационный портал, посвященный
ситуации в Тибете и жизни тибетцев. Содержит ряд полезных ссылок на
новостные сайты.
