---
title: "Занятия по тибетской йоге"
back: '/classes/'
---

Тибетская йога, практикуемая в нашем центре - это комплекс упражнений, который
передал ученикам лама Таши Гьяцо. В Москве занятия проводятся с лета 2005 года.

Что же такое тибетская йога и чем она отличается от других видов йоги?
Существует много разных школ и, соответственно, разных видов йоги. Например,
в Индии много разных ашрамов и других мест, где занимаются йогой, и почти
в каждом из них занимаются каким-то своим видом йоги, т.е. существуют различные
направления йоги, и среди них есть как какие-то схожие моменты, так и сильно
отличающиеся. Тибетская йога, практикуемая в нашем Центре, - один из видов
йоги, пришедший к нам из Тибета, из монастыря Лавран благодаря ламе Таши Гьяцо.
Упражнения по форме напоминают как многое из индийской йоги, так и некоторые
элементы цигун, что и понятно: Тибет находится между Индией и Китаем,
и сказывается взаимное влияние различных школ и направлений. Среди упражнений
есть упражнения с дыханием, визуализацией и, конечно же, упражнения на гибкость
и растяжку. И ещё, пожалуй, самый важный момент, на который обращает особое
внимание лама Таши Гьяцо, - это сосредоточение, концентрация внимания на
выполняемом упражнении. Без концентрации внимания не будет должного эффекта,
и упражнения мало чем будут отличаться от обычной физкультуры.

Польза от тибетской йоги: улучшение здоровья, самочувствия, улучшение обменных
процессов, нормализация работы внутренних органов и т.п. Также улучшается
внимание, сосредоточенность, совершенствуется поза для медитации, т.е.
становится проще сидеть в позе лотоса с прямой спиной, что бывает важно при
выполнении многих буддийских практик. Лама Таши Гьяцо говорит, что, если вы
хотите быть здоровыми, меньше болеть, то занимайтесь йогой, и тогда лекарства
вам будут практически не нужны. Ученики, которые регулярно занимаются йогой
в нашем Центре, отмечают, что стали меньше болеть и уставать на работе.
Некоторые естественным образом избавились от лишнего веса.

Занятия в нашем Центре проходят трижды в неделю. Приходить на занятия можно
всем желающим. Когда люди приходят впервые, им даются объяснения по
упражнениям. Продолжительность занятия примерно 1 час 40 мин. Стоимость одного занятия
в настоящее время составляет *200 руб.*; для малоимущих, студентов и пенсионеров
- *100 руб.*

[.stretched]
flickr::139340494@N02/albums/72157661165270214[]

=== Другие материалы:

* link:yoga-booklet.pdf[Книга с упражнениями по тибетской йоге] [pdf, 5Мб]
* link:/text/yoga-gymnastics-for-body-and-soul/[Йога – гимнастика для души и тела]
* link:/text/yoga-faq/[Наиболее часто задаваемые вопросы и ответы по тибетской йоге]
